# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Stuff & Nonsense
tagline:             'Bits of Python, bioinformatics and such from <a href="https://twitter.com/sandyjmacdonald" target="_blank">@sandyjmacdonald</a>'
description:         'Bits of Python, bioinformatics and such from <a href="https://twitter.com/sandyjmacdonald" target="_blank">@sandyjmacdonald</a>.'
url:                 http://sandyjmacdonald.github.io
baseurl:             /
paginate:            5

# About/contact
author:
  name:              Sandy Macdonald
  url:               https://twitter.com/sandyjmacdonald
  email:             

# Custom vars
version:             1.1.0